import librosa
import matplotlib.pyplot as plt
import numpy as np

# load audio as a wavefrom:
file_path = "Audio.opus"
y , sr = librosa.load(file_path, sr=22050) # 22000 waves generate from audio, y are features generated by audio
print("Sample Rate is: ", sr)
print("Audio array shape is: ",y.shape)

# plotting waves:
plt.figure(figsize=(12,4))
librosa.display.waveshow(y, sr=sr)
plt.title("Time(s)")
plt.ylabel("Amplitude")
plt.show()

# Compute short-time fourier transformation(STFT:
D = librosa.stft(y)
# convert amplitude into decibels
s_db = librosa.amplitude_to_db(abs(D), ref=np.max)
plt.figure(figsize=(12,4))
librosa.display.specshow(s_db, sr=sr, x_axis='time', y_axis='log')  # normalize voive
plt.colorbar(format='%+2.0f dB')   # through colors it will ectract features-> every colour represents a number
plt.title("Spectrogram (dB)")
plt.show()

#---------------------------------------------------------------
# Extract 13 MFCCs Mel-frequency cepstral coefficient
mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
plt.figure(figsize=(10,4))
librosa.display.specshow(mfccs, sr=sr,x_axis='time', y_axis='log')
plt.colorbar()
plt.title("MFCC")
plt.show()

#--------------------------------------------------------
# Extract Chromogram
chromo = librosa.feature.chroma_stft(y=y, sr=sr)
plt.figure(figsize=(10,4))
librosa.display.specshow(mfccs, sr=sr,x_axis='time', y_axis='chroma')
plt.colorbar()
plt.title("Chromogram")
plt.show()

#--------------------------------------------------------
spectral_centroid = librosa.feature.spectral_centroid(y=y, sr=sr)[0]
# plot waveform and spectral centroidplt.figure(figsize=(10,4))
plt.figure(figsize=(12,4))
plt.semilogy(spectral_centroid, color='r',label='Spectral Centroid')
librosa.display.waveshow(y,sr=sr,alpha=0.5)
plt.legend(loc='upper right')
plt.title("Spectral Centroid")
plt.show()

#--------------------------------------------------------
spectral_rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr, roll_percent=0.85)[0]
plt.figure(figsize=(12,4))
librosa.display.waveshow(y,sr=sr,alpha=0.5)
plt.plot(spectral_rolloff, color='r', label='Spectral Rolloff')
plt.legend(loc='upper right')
plt.title("Spectral Rolloff")
plt.show()